baseURL = "https://dis2019.github.io/"
languageCode = "en-us"
title = "DIS 2019"
theme = "gohugo-theme-ananke"
    
[params]
    description = "Designing Interactive Systems (DIS) 2019: Contesting Borders and Intersections"
    #background_color_class = "bg-light-red"
    featured_image = '/images/pinkMountainsCity.png'
    body_classes = "helvetica bg-near-white"